# test pipline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls
  displayName: 'list working dir'
- script: test -e ./playbook-pack-init.sh
  continueOnError: false
  displayName: 'check playbook-pack-init script is present'
- script: shellcheck -V
  continueOnError: false
  displayName: 'show shellcheck version'
- script: shellcheck playbook-pack-init.sh
  continueOnError: false
  displayName: 'run shellcheck'
- script: mkdir test
  continueOnError: false
  displayName: 'make test dir'
- script: ../playbook-pack-init.sh -s
  workingDirectory: ./test
  displayName: 'run playbook-pack-init script'
- script: ls
  workingDirectory: ./test
  displayName: 'list working dir'
