# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls
  displayName: 'list working dir'
- script: test -e ./playbook-pack-init.sh
  continueOnError: false
  displayName: 'check playbook-pack-init script is present'
- script: shellcheck -V
  continueOnError: false
  displayName: 'show shellcheck version'
- script: shellcheck playbook-pack-init.sh
  continueOnError: false
  displayName: 'run shellcheck'